Repository tmobile/magtape, pull requests merged in 2020-10, with the labels that each got.

#51 Hardcode Gunicorn Workers/Threads
  app/magtape/config.py
  deploy/install.yaml
  deploy/manifests/kustomization.yaml
  deploy/manifests/magtape-hpa.yaml
  deploy/overlays/development/hpa-patch.yaml
  deploy/overlays/development/kustomization.yaml
  hack/build-single-manifest.sh
Labels: bug, enhancement, yaml

#52 Implement securityContext and non-root config
  deploy/install.yaml
  deploy/manifests/magtape-deploy.yaml
Labels: enhancement, kubernetes, yaml

#53 Prepare v2.2.0 release
  CHANGELOG.md
  Makefile
  deploy/install.yaml
  deploy/manifests/magtape-deploy.yaml
Labels: release

#60 Cleanup Rego testing/mocking
  CONTRIBUTING.md
  Makefile
  docs/policies.md
  policies/test/test_policy-emptydir-check.rego
  policies/test/test_policy-emptydir-check_mock.json
  policies/test/test_policy-host-path-check.rego
  policies/test/test_policy-host-path-check_mock.json
  policies/test/test_policy-host-port-check.rego
  policies/test/test_policy-host-port-check_mock.json
  policies/test/test_policy-liveness-probe-check.rego
  policies/test/test_policy-liveness-probe-check_mock.json
  policies/test/test_policy-node-port-range-check.rego
  policies/test/test_policy-node-port-range-check_mock.json
  policies/test/test_policy-pdb-check.rego
  policies/test/test_policy-pdb-check_mock.json
  policies/test/test_policy-port-name-mismatch-check.rego
  policies/test/test_policy-port-name-mismatch-check_mock.json
  policies/test/test_policy-privileged-pod-check.rego
  policies/test/test_policy-privileged-pod-check_mock.json
  policies/test/test_policy-readiness-probe-check.rego
  policies/test/test_policy-readiness-probe-check_mock.json
  policies/test/test_policy-resource-limits-check.rego
  policies/test/test_policy-resource-limits-check_mock.json
  policies/test/test_policy-resource-requests-check.rego
  policies/test/test_policy-resource-requests-check_mock.json
  policies/test/test_policy-singleton-pod-check.rego
  policies/test/test_policy-singleton-pod-check_mock.json
Labels: documentation, enhancement, policy, rego

#62 Updating to docker/build-push-action@v2
  .github/workflows/ci-e2e-checks.yaml
  .github/workflows/ci-image-build.yaml
Labels: ci, enhancement, gh-actions

#66 Surface server-side warnings
  CHANGELOG.md
  app/magtape/magtape.py
Labels: enhancement, python

#70 Prepare v2.2.1 Fix Release
  .github/workflows/ci-codeql-analysis.yml
  .github/workflows/ci-e2e-checks.yaml
  .github/workflows/ci-image-build.yaml
  .github/workflows/ci-manifest-checks.yaml
  .github/workflows/ci-python-checks.yaml
  .github/workflows/ci-rego-checks.yaml
  .github/workflows/ci-std-checks.yaml
  Makefile
  app/magtape-init/Pipfile.lock
  deploy/install.yaml
  deploy/manifests/magtape-deploy.yaml
Labels: release, security-fix
